# DO NOT EDIT THIS FILE!
#
# Python module AutoTest generated by omniidl

import omniORB
omniORB.updateModule("AutoTest")

# ** 1. Stub files contributing to this module
import AutoTestService_idl

# ** 2. Sub-modules

# ** 3. End
