# DO NOT EDIT THIS FILE!
#
# Python module AutoTest__POA generated by omniidl

import omniORB
omniORB.updateModule("AutoTest__POA")

# ** 1. Stub files contributing to this module
import AutoTestService_idl

# ** 2. Sub-modules

# ** 3. End
