# DO NOT EDIT THIS FILE!
#
# Python module RTC generated by omniidl

import omniORB
omniORB.updateModule("RTC")

# ** 1. Stub files contributing to this module
import BasicDataType_idl
import ExtendedDataTypes_idl
import InterfaceDataTypes_idl
import RTC_idl

# ** 2. Sub-modules

# ** 3. End
