# DO NOT EDIT THIS FILE!
#
# Python module OpenRTM__POA generated by omniidl

import omniORB
omniORB.updateModule("OpenRTM__POA")

# ** 1. Stub files contributing to this module
import DataPort_idl
import OpenRTM_idl

# ** 2. Sub-modules

# ** 3. End
