# DO NOT EDIT THIS FILE!
#
# Python module SimpleService__POA generated by omniidl

import omniORB
omniORB.updateModule("SimpleService__POA")

# ** 1. Stub files contributing to this module
import MyService_idl

# ** 2. Sub-modules

# ** 3. End
