# DO NOT EDIT THIS FILE!
#
# Python module RTM generated by omniidl

import omniORB
omniORB.updateModule("RTM")

# ** 1. Stub files contributing to this module
import Manager_idl

# ** 2. Sub-modules

# ** 3. End
